---

- name: Tmate-slave | Clone repo
  git:
    repo: "{{ tmate_slave_repo }}"
    dest: "{{ tmate_slave_source }}"

- name: Tmate-slave | Create keys
  shell: ./create_keys.sh && mv keys "{{ tmate_slave_keys }}"
  args:
    chdir: "{{ tmate_slave_source }}"
    creates: "{{ tmate_slave_keys }}/ssh_host_rsa_key"

- name: Tmate-slave | Compile server
  shell: ./autogen.sh && ./configure && make && make install
  args: 
    chdir: "{{ tmate_slave_source }}"
    creates: "{{ tmate_slave_prefix }}/tmate-slave"
